ARG NODE_VERSION=20.11.0

FROM node:${NODE_VERSION}-slim AS base
ENV NODE_ENV=development
WORKDIR /src

FROM base AS build
COPY --link package.json package-lock.json ./
RUN npm install

FROM base
COPY --from=build /src/node_modules /src/node_modules
CMD [ "npm", "run", "dev" ]

# Retrived from https://markus.oberlehner.net/blog/running-nuxt-3-in-a-docker-container/