services:
  twcg-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5005:5432'
    volumes:
      - twcg-db:/var/lib/postgresql/data
volumes:
  twcg-db:
    driver: local
