services:
  postgres:
    container_name: database
    image: paradedb/paradedb:latest
    hostname: localhost
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5005:5432"
    volumes:
      - hrm-db:/var/lib/postgresql/data
volumes:
  hrm-db:
    driver: local
