name: hrm-resources
services:
  postgres:
    container_name: database
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "HRM-postgres:/var/lib/postgresql/data"
    restart: unless-stopped
volumes:
  HRM-postgres:
# References:
# https://medium.com/@jewelski/quickly-set-up-a-local-postgres-database-using-docker-5098052a4726
